on:
  push:
    paths:
      - 'backend_redis/**'


jobs:
  deploy-redis-to-ECR:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: project2-v1
      REDIS_SERVICE_NAME: redis
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Connect to ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}


      - name: build and push
        run: |
          docker build -t backend_redis:latest -f backend_redis/Dockerfile backend_redis
          docker tag backend_redis:latest ${{ secrets.ECR_REDIS }}:latest
          docker push ${{ secrets.ECR_REDIS }}:latest

      - name: Deploy Redis to ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $REDIS_SERVICE_NAME --force-new-deployment